export const LocalKey = {
  USER_INFO: "user_info",
  JWT_AUTHORIZATION: "jwt",
  ACCESS_TOKEN_LOCALKEY: "access_token",
};

export const mutationKeys = {
  MUTATION_LOGIN: "mutation_login",
  MUTATION_ADD_RECIPIENTS_TO_GROUP: "MUTATION_ADD_RECIPIENTS_TO_GROUP",
  MUTATION_LEAVE_GROUP: "MUTATION_LEAVE_GROUP",
  MUTATION_UPDATE_GROUP: "MUTATION_UPDATE_GROUP",
  MUTATION_CREATE_MESSAGE: "MUTATION_CREATE_MESSAGE",
  MUTATION_CREATE_GROUP_MESSAGE: "MUTATION_CREATE_GROUP_MESSAGE",
  MUTATION_CREATE_MESSAGE_REQUEST: "MUTATION_CREATE_MESSAGE_REQUEST",
  MUTATION_CREATE_CONFESSION: "MUTATION_CREATE_CONFESSION",
  MUTATION_CREATE_TAG: "MUTATION_CREATE_TAG",
  MUTATION_CREATE_POST: "MUTATION_CREATE_POST",
  MUTATION_CREATE_NOTE: "MUTATION_CREATE_NOTE",
  MUTATION_ACCEPT_CONVERSATION_REQUEST: "MUTATION_ACCEPT_CONVERSATION_REQUEST",
  MUTATION_UPDATE_TAG: "MUTATION_UPDATE_TAG",
  MUTATION_UPDATE_NOTE: "MUTATION_UPDATE_NOTE",
};

export const queryKeys = {
  GET_LIST_INFINITE_CONVERSATIONS: "GET_LIST_INFINITE_CONVERSATIONS",

  GET_LIST_INFINITE_GROUP_CONVERSATIONS:
    "GET_LIST_INFINITE_GROUP_CONVERSATIONS",

  GET_LIST_INFINITY_GROUPS: "GET_LIST_INFINITY_GROUPS",

  GET_LIST_INFINITE_FRIENDS: "GET_LIST_INFINITE_FRIENDS",

  GET_LIST_INFINITE_GROUP_MESSAGES: "GET_LIST_INFINITE_GROUP_MESSAGES",

  GET_LIST_INFINITE_FRIEND_REQUESTS: "GET_LIST_INFINITE_FRIEND_REQUESTS",

  GET_LIST_INFINITE_LOCATIONS: "GET_LIST_INFINITE_LOCATIONS",

  GET_LIST_INFINITE_PREFER_GENDERS: "GET_LIST_INFINITE_PREFER_GENDERS",

  GET_LIST_INFINITE_NOTES: "GET_LIST_INFINITE_NOTES",

  GET_LIST_INFINITY_NOTES: "GET_LIST_INFINITY_NOTES",

  GET_LIST_INFINITE_TAGS: "GET_LIST_INFINITE_TAGS",

  GET_LIST_INFINITE_MESSAGES: "GET_LIST_INFINITE_MESSAGES",

  GET_LIST_INFINITE_POSTS: "GET_LIST_INFINITE_POSTS",

  GET_LIST_INFINITE_CONFESSIONS: "GET_LIST_INFINITE_CONFESSIONS",

  GET_USER_PROFILE: "GET_USER_PROFILE",
};
