export const LocalKey = {
  USER_INFO: "user_info",
  JWT_AUTHORIZATION: "jwt",
  ACCESS_TOKEN_LOCALKEY: "access_token",
};

export const mutationKeys = {
  MUTATION_LOGIN: "mutation_login",
  MUTATION_CREATE_MESSAGE: "MUTATION_CREATE_MESSAGE",
  MUTATION_ACCEPT_CONVERSATION_REQUEST: "MUTATION_ACCEPT_CONVERSATION_REQUEST",
};

export const queryKeys = {
  GET_LIST_INFINITE_CONVERSATIONS: "GET_LIST_INFINITE_CONVERSATIONS",

  GET_LIST_INFINITE_MESSAGES: "GET_LIST_INFINITE_MESSAGES",

  GET_LIST_INFINITE_POSTS: "GET_LIST_INFINITE_POSTS",
};
