export const LocalKey = {
  USER_INFO: "user_info",
  JWT_AUTHORIZATION: "jwt",
  ACCESS_TOKEN_LOCALKEY: "access_token",
};

export const mutationKeys = {
  MUTATION_LOGIN: "mutation_login",
  MUTATION_ADD_RECIPIENTS_TO_GROUP: "MUTATION_ADD_RECIPIENTS_TO_GROUP",
  MUTATION_LEAVE_GROUP: "MUTATION_LEAVE_GROUP",
  MUTATION_UPDATE_GROUP: "MUTATION_UPDATE_GROUP",
  MUTATION_CREATE_MESSAGE: "MUTATION_CREATE_MESSAGE",
  MUTATION_CREATE_GROUP_MESSAGE: "MUTATION_CREATE_GROUP_MESSAGE",
  MUTATION_CREATE_MESSAGE_REQUEST: "MUTATION_CREATE_MESSAGE_REQUEST",
  MUTATION_CREATE_CONFESSION: "MUTATION_CREATE_CONFESSION",
  MUTATION_CREATE_TAG: "MUTATION_CREATE_TAG",
  MUTATION_CREATE_POST: "MUTATION_CREATE_POST",
  MUTATION_CREATE_NOTE: "MUTATION_CREATE_NOTE",
  MUTATION_ACCEPT_CONVERSATION_REQUEST: "MUTATION_ACCEPT_CONVERSATION_REQUEST",
  MUTATION_REJECT_FRIEND_REQUEST: "MUTATION_REJECT_FRIEND_REQUEST",
  MUTATION_ACCEPT_FRIEND_REQUEST: "MUTATION_ACCEPT_FRIEND_REQUEST",
  MUTATION_CANCEL_FRIEND_REQUEST: "MUTATION_CANCEL_FRIEND_REQUEST",
  MUTATION_UPDATE_TAG: "MUTATION_UPDATE_TAG",
  MUTATION_UPDATE_NOTE: "MUTATION_UPDATE_NOTE",
  MUTATION_CREATE_ACCOUNT: "MUTATION_CREATE_ACCOUNT",
  MUTATION_UPDATE_USER_PROFILE: "MUTATION_UPDATE_USER_PROFILE",
  MUTATION_FIND_NEW_FRIEND: "MUTATION_FIND_NEW_FRIEND",
  MUTATION_CREATE_ALLEY: "MUTATION_CREATE_ALLEY",
  MUTATION_LEAVE_CONVERSATION: "MUTATION_LEAVE_CONVERSATION",
  MUTATION_ACCEPT_REPORT_TICKET: "MUTATION_ACCEPT_REPORT_TICKET",
  MUTATION_REJECT_REPORT_TICKET: "MUTATION_REJECT_REPORT_TICKET",
  MUTATION_CREATE_REPORT_TICKET: "MUTATION_CREATE_REPORT_TICKET",
};

export const queryKeys = {
  GET_LIST_INFINITE_CONVERSATIONS: "GET_LIST_INFINITE_CONVERSATIONS",

  GET_LIST_INFINITE_GROUP_CONVERSATIONS:
    "GET_LIST_INFINITE_GROUP_CONVERSATIONS",

  GET_LIST_INFINITY_GROUPS: "GET_LIST_INFINITY_GROUPS",

  GET_LIST_INFINITE_FRIENDS: "GET_LIST_INFINITE_FRIENDS",

  GET_LIST_INFINITE_GROUP_MESSAGES: "GET_LIST_INFINITE_GROUP_MESSAGES",

  GET_LIST_INFINITE_FRIEND_REQUESTS: "GET_LIST_INFINITE_FRIEND_REQUESTS",

  GET_LIST_INFINITE_LOCATIONS: "GET_LIST_INFINITE_LOCATIONS",

  GET_LIST_INFINITE_PREFER_GENDERS: "GET_LIST_INFINITE_PREFER_GENDERS",

  GET_LIST_INFINITE_NOTES: "GET_LIST_INFINITE_NOTES",

  GET_LIST_INFINITY_NOTES: "GET_LIST_INFINITY_NOTES",

  GET_LIST_INFINITE_TAGS: "GET_LIST_INFINITE_TAGS",

  GET_LIST_INFINITE_MESSAGES: "GET_LIST_INFINITE_MESSAGES",

  GET_LIST_INFINITE_POSTS: "GET_LIST_INFINITE_POSTS",

  GET_LIST_INFINITE_CONFESSIONS: "GET_LIST_INFINITE_CONFESSIONS",

  GET_USER_PROFILE: "GET_USER_PROFILE",

  GET_FIRST_ALLEY: "GET_FIRST_ALLEY",

  GET_ALLEYS_BY_PARENT: "GET_ALLEYS_BY_PARENT",

  GET_GROUP_BY_ALLEY_ID: "GET_GROUP_BY_ALLEY_ID",

  GET_DETAILS_PUBLIC_GROUP: "GET_DETAILS_PUBLIC_GROUP",

  GET_DETAILS_ALLEY: "GET_DETAILS_ALLEY",

  GET_DETAILS_PRIVATE_GROUP: "GET_DETAILS_PRIVATE_GROUP",

  GET_LIST_REPORT_TICKETS: "GET_LIST_REPORT_TICKETS",

  GET_DETAILS_REPORT_TICKET: "GET_DETAILS_REPORT_TICKET",
};
