version: "3.8"
services:
  web:
    depends_on:
      - api
    build: ./anfie-client
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./anfie-client/package.json
          action: rebuild
        - path: ./anfie-client/package-lock.json
          action: rebuild
        - path: ./anfie-client
          target: /app
          action: sync

  api:
    depends_on:
      - dev-db
    build: ./anfie-server
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: ./anfie-server/package.json
          action: rebuild
        - path: ./anfie-server/package-lock.json
          action: rebuild
        - path: ./anfie-server
          target: /app
          action: sync

  openai-service:
    image: pawanosman/chatgpt:latest
    ports:
      - "3040:3040"

  dev-db:
    image: postgres
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=anfie
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
